---
title: "R Notebook"
output: html_notebook
---
```{r}
activity_patient_demographics %>% 
  distinct(admission_type)


specialty_admissions <- read_csv("/Users/anominity/Desktop/CodeClan/gitgroup/phs_group_project/02_cleaned_data/admissions_by_speciality_clean.csv")

bed_admissions %>% 
  filter(hb_name == "NHS Ayrshire and Arran",
         specialty == "All") %>% 
  ggplot() +
  aes(x = week_ending, y = number_admissions) +
  geom_line(aes(colour = hb_name), show.legend = FALSE)
  


bed_admissions %>% 
  filter(hb_name == "NHS Ayrshire and Arran",
         specialty == "All") %>% 
  summarise(n())
```

```{r}
bed_admissions %>% 
  filter(specialty == "All", 
         hb == "S08000015",
         admission_type == "All",
         between(week_ending, min(week_ending), max(week_ending))) %>%  
  ggplot() +
  geom_line(aes(x = week_ending, y = number_admissions)) +
  geom_line(aes(x = week_ending, average20182019, colour = "red"))

class(bed_admissions$week_ending)
unique(bed_admissions$specialty)
unique(bed_admissions$admission_type)
```

