---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(rgeos)
library(leaflet)
library(sf)
library(tsibble)
library(lubridate)
```



```{r}
beds <- read_csv(here::here("02_cleaned_data/bed_clean.csv")) %>% 
  mutate(year_quarter = yearquarter(year_quarter))
```




```{r}
temp %>%  distinct(HB)
```





```{r}
bbox <- st_bbox(nhs_borders) %>% 
  as.vector()

leaflet(nhs_borders) %>% 
  addPolygons(fillColor = ~pal(HBCode),
              fillOpacity = 1,
              weight = 1, 
              color = "white",
              label = labels,
              labelOptions = labelOptions(),
              highlightOptions = highlightOptions(color = "#666",
                                                  weight = 5,
                                                  bringToFront = TRUE)) %>% 
  setMaxBounds(bbox[1], bbox[2], bbox[3], bbox[4])
```





```{r}
# Load in the region geometry
nhs_borders <- st_read(dsn = "../01_data/geospatial_data/SG_NHS_HealthBoards_2019/", 
                       layer = "SG_NHS_HealthBoards_2019") %>% 
  st_simplify(dTolerance = 2500) %>% 
  st_transform('+proj=longlat +datum=WGS84')

# 
# st_write(nhs_borders,
#          dsn = here::here("02_cleaned_data/nhs_region_simple"),
#          driver = "ESRI Shapefile")
```

```{r}
temp_select <- beds %>% 
  select(contains(c("bed", "occup"))) %>%  names()


input <- list(year_quarter = c("2019 Q3", "2019 Q4"),
              speciality_name = "All Specialties",
              variable_to_plot = temp_select[1])

# region_selected <- input$region$id


heatmap_data <- beds %>% 
  filter(year_quarter >= yearquarter(input$year_quarter[1]) &
           year_quarter <= yearquarter(input$year_quarter[2]),
         specialty_name == input$speciality_name) %>% 
  group_by(HBCode = hb) %>% 
  select(!!as.name(input$variable_to_plot)) %>% 
  summarise(plot_this = mean(!!as.name(input$variable_to_plot), na.rm = TRUE))



a_shape <- sp::merge(nhs_borders, heatmap_data, by = c("HBCode" = "HBCode"))

range <- c(signif(min(a_shape$plot_this),1), 
           ceiling(max(a_shape$plot_this)/10^ceiling(log10(max(a_shape$plot_this))-2)) *10^ceiling(log10(max(a_shape$plot_this))-2)) 
           

bins <- seq(from = range[1], to = range[2], by = (range[2] - range[1])/9)

hot_colour <- colorBin(palette = "YlOrRd", domain = a_shape$plot_this, bins = bins)

hot_colour(a_shape$plot_this)

leaflet(a_shape) %>% 
  addTiles() %>% 
  addPolygons(fillColor = ~hot_colour(plot_this),
              fillOpacity = 1,
              weight = 1, 
              color = "black",
              dash = 4) %>% 
  addMarkers(layerId = "Scotland",lng = -7 ,lat = 58.7) %>% 
  addLegend(pal = hot_colour,
            values = ~plot_this, title = input$variable_to_plot,
            position = "bottomright") %>% 
  setMaxBounds(bbox[1], bbox[2], bbox[3], bbox[4])

  
```


```{r}



leaflet(nhs_borders) %>% 
  addPolygons(fillColor = ~pal(HBCode),
              fillOpacity = 1,
              weight = 1, 
              color = "white",
              label = labels,
              labelOptions = labelOptions(),
              highlightOptions = highlightOptions(color = "#666",
                                                  weight = 5,
                                                  bringToFront = TRUE)) %>% 
  setMaxBounds(bbox[1], bbox[2], bbox[3], bbox[4])

```




```{r}
temp_select <- beds %>% 
  select(contains(c("bed", "occup"))) %>%  names()


input <- list(year_quarter = c("2019 Q3", "2019 Q4"),
              speciality_name = "All Specialties",
              variable_to_plot = temp_select[1])

beds %>% 
  filter(year_quarter >= yearquarter(input$year_quarter[1]) &
           year_quarter <= yearquarter(input$year_quarter[2]),
         specialty_name == input$speciality_name) %>% 
  group_by(HBCode = hb) %>% 
  select(!!as.name(input$variable_to_plot)) %>% 
  summarise( case_when(
    str_detect(input$variable_to_plot, "_beds") ~ mean(!!as.name(input$variable_to_plot)),
    str_detect(input$variable_to_plot, "th_of_st") ~ sum(stays)/sum(length_of_stay)*100,
    str_detect(input$variable_to_plot, "th_of_ep") ~ sum(episodes)/sum(length_of_episode)*100,
    str_detect(input$variable_to_plot, "percent_occ") ~ 100*sum(total_occupied_beddays)/sum(all_staffed_beddays),
    TRUE ~ sum(!!as.name(input$variable_to_plot))
  )
  )
```

```{r}
beds %>% select(contains(c("bed", "occup"))) %>%  names()
activity_dep_variables
```


```{r}
beds %>% select(contains(c("bed", "occup"))) %>% 
  mutate(new_percent = 100*total_occupied_beddays/all_staffed_beddays) %>% 
  mutate(test = percentage_occupancy - new_percent) %>% 
  slice_max(test)
```


```{r}
activity_deprivation %>% 
  mutate(new_av_stays = length_of_stay/stays,
         new_av_episode = length_of_episode/episodes,
         test1_ep = new_av_episode - average_length_of_episode,
         test2_stay = new_av_stays - average_length_of_stay) %>% 
  select(test1_ep, test2_stay) %>% 
  slice_max(test2_stay)
```



```{r}
beds %>% 
  select(contains(c("bed", "occup"))) %>%  
  names() %>% 
  lapply()
```

```{r}
activity_deprivation
```

```{r}
eval(as.name("beds"))$hb


```

```{r}
bb
log10(bb)
10^ceiling(log10(bb))
signif(bb, 1)
```

```{r}
bb <- c(range[1], range[2])
bb
signif(bb, 1)
c(signif(range[1], 1), range[2])

ceiling(range[2]/10^ceiling(log10(range[2])-2)) *10^ceiling(log10(range[2])-2)
```

```{r}
bb <- 4850
signif(bb, 1)
floor(bb/10^ceiling(log10(bb)-2)) *10^ceiling(log10(bb)-2)



significance_round(bb, round_up = FALSE, 2)
```

```{r}
significance_round <- function(x, round_up = TRUE, digits = 1){
  
  if(round_up){
    ceiling(x/10^ceiling(log10(x)- digits)) *10^ceiling(log10(x)- digits)
  }else{
    floor(x/10^ceiling(log10(x)- digits)) *10^ceiling(log10(x)-digits)
  }
  
}
```

```{r}

significance_round(c(0.458, 1526), round_up = FALSE, digits = 2)
```

```{r}
activity_deprivation %>% 
  mutate(year_quarter = make_yearquarter(year, quarter), .after = quarter)
```

```{r}
activity_dep_variables <- activity_deprivation %>% 
  select(contains(c("episode", "stay"))) %>%  names()

names(activity_dep_variables) <- str_to_title(
  str_replace_all(
    str_replace(
      str_replace(activity_dep_variables, 
                  "^e", "number of e"), "^s", "number of s"), "_", " "))
```

```{r}
inpute <- list(data_select_geo = "activity_deprivation")
eval(as.name(inpute$data_select_geo))
```

```{r}
significance_round(0, round_up = TRUE , 2)
```



```{r}
range <- c(0,0)

seq(from = range[1], to = range[2], by = (range[2] - range[1])/9) %>% 
        signif(3)
```

```{r}
names(activity_dep_variables[str_which()])

```



```{r}
specialty_admissions %>% 
  distinct(hb_name, hb)
```

```{r}
names(which(activity_dep_variables == "stays"))
case_when(
  input$data_select_geo == "beds" ~ names(which(activity_dep_variables == input$variable_to_plot_geo))
  TRUE ~ names(which(activity_dep_variables == input$variable_to_plot_geo))
)
```

```{r}
input <- list(variable_to_plot_geo = "all_staffed_beddays",
              data_select_geo = "beds")

if_else(input$data_select_geo == "beds",
                     names(which(beds_variables_selection == input$variable_to_plot_geo)), 
                     names(which(activity_dep_variables == input$variable_to_plot_geo)))
```

