# Required packages ####
```{r}
library(prob)
library(tidyverse)
library(janitor)
library(assertr)
library(fastGraph)
library(tsibble)
library(tsibbledata)
library(e1071)
library(leaflet)
library(infer)
library(shiny)
```
# Required datasets ####
```{r}
hospital_beds <- read_csv('hospital_covid_data/beds_by_nhs_board_of_treatment_and_specialty.csv') %>% clean_names()
hospital_admissions <- read_csv('hospital_covid_data/hospital_admissions_hb_simd_20220302.csv') %>% clean_names()
  hospital_demographics <- read_csv('hospital_covid_data/hospital_admissions_hscp_agesex_20220302(2).csv') %>% clean_names()
waiting_times <- read_csv('hospital_covid_data/monthly_ae_waitingtimes_202206.csv') %>% clean_names()
hospital_specialty <- read_csv('hospital_covid_data/inpatient_and_daycase_by_nhs_board_of_treatment_and_specialty.csv') %>% clean_names()
hospital_inpatients <- read_csv('hospital_covid_data/inpatient_and_daycase_by_nhs_board_of_treatment_age_and_sex.csv') %>% clean_names()
```

```{r}
locations <- read_csv('hospital_covid_data/current-hospital_flagged20211216.csv') %>% clean_names()

full_bed_data <- left_join(locations, hospital_beds, by = c("location"))
```

```{r}
waiting_times_update <- read_csv('hospital_covid_data/a&e_waiting_times.csv') %>% clean_names()
```
# First graph for bed data ####
```{r}
bed_graph <- hospital_beds %>% 
  select(quarter, all_staffed_beddays) %>% 
  # group_by_key() %>% 
  group_by(quarter) %>% 
  ggplot() +
  geom_col(aes(x = quarter, y = all_staffed_beddays), fill = "blue") +
  theme(axis.text.x = element_text(angle = 90))
bed_graph
```
# First graph for demographic data ####
```{r}
demo_graph <- hospital_demographics %>% 
  select(age_group, sex, number_admissions) %>% 
  group_by(age_group) %>% 
  ggplot() +
  geom_col(aes(x = age_group, y = number_admissions, fill = sex)) +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Admissions per age and gender")
demo_graph
```

```{r}
# waiting_graph <- waiting_times %>% 
#   select(department_type, number_of_attendances_aggregate) %>% 
#   group_by(department_type) %>% 
#   summarise(total_attendances = sum(number_of_attendances_aggregate)) %>% 
#   ggplot() +
#   geom_col(x = department_type, y = total_attendances) +
#   theme(axis.text.x = element_text(angle = 90))
  
```
# First attempt at rolling data graph ####
```{r}
library(slider)
rolling_data <- hospital_admissions %>% 
  mutate(
    admin_moving_avg = slide_dbl(
      .x = number_admissions,
      .f = ~mean(.x, na.rm = TRUE),
      .before = 1000,
      .after = 1000,
      .complete = TRUE
    )
  )

ggplot(rolling_data) +
  geom_line(aes(x = admission_type, y = number_admissions), colour = "grey") +
  geom_line(aes(x = admission_type, y = admin_moving_avg), colour = "green")

rolling_data_2019 <- hospital_admissions %>% 
  mutate(
    admin_moving_avg2 = slide_dbl(
      .x = average20182019,
      .f = ~mean(.x),
      before = 1000,
      after = 1000,
      .complete = TRUE
    )
  )
ggplot(rolling_data_2019) +
  geom_line(aes(x = admission_type, y = average20182019), colour = "grey") +
  geom_line(aes(x = admission_type, y = admin_moving_avg2), colour = "blue")
```

```{r}
# specialty_graph <- hospital_specialty %>%
#   group_by_key() %>% 
#   group_by(admission_type) %>% 
#   ggplot() +
#   geom_col(x = admission_type, y = episodes, fill = location) +
#   theme(axis.text.x = element_text(angle = 90))  
  
```

```{r}
full_wards <- hospital_beds %>% 
  select(location, specialty_name, quarter, percentage_occupancy) %>% 
  filter(percentage_occupancy == "100") %>% 
  group_by(quarter, location) %>% 
  summarise(total_full_wards = n()) %>% 
  ggplot() +
  geom_col(aes(x = quarter, y = total_full_wards)) +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Full wards per quarter")

full_wards
```

```{r}
bed_graph_pre_2020 <- hospital_beds %>% 
  # group_by_key() %>% 
  group_by(quarter) %>% 
  filter(quarter < "2020") %>% 
  ggplot() +
  geom_col(aes(x = quarter, y = all_staffed_beddays)) +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Number of beddays prior to 2020")
bed_graph_pre_2020  
```

```{r}
admission_trends <- hospital_admissions %>% 
  select(admission_type, hb, week_ending, number_admissions) %>% 
  group_by(hb) %>% 
  ggplot() +
  geom_col(aes(x = week_ending, y = number_admissions, fill = hb)) +
  theme(axis.text.x = element_text(angle = 0))
admission_trends
```

```{r}
elective_v_emergency <- hospital_inpatients %>% 
  filter(admission_type %in% c("Elective Inpatients", "Emergency Inpatients")) %>%
  # filter(AdmissionType == "Emergency Inpatients") %>% 
  group_by(admission_type) %>% 
  summarise(total_stays = sum(stays)) %>% 
  ggplot() +
  geom_col(aes(x = admission_type, y = total_stays)) +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Elective V Emergency inpatients")
elective_v_emergency
```

```{r}
mean_admissions <- hospital_demographics %>% 
  group_by(admission_type) %>% 
  summarise(mean_admissions = mean(number_admissions)) %>% 
  
  ggplot() +
  geom_col(aes(x = admission_type, y = mean_admissions)) +
  theme(axis.text.x = element_text(angle = 90))
mean_admissions

mean_admissions_2019 <- hospital_demographics %>% 
  group_by(admission_type) %>% 
  summarise(mean_2019 = mean(average20182019)) %>% 
  ggplot() +
  geom_col(aes(x = admission_type, y = mean_2019)) +
  theme(axis.text.x = element_text(angle = 90))
mean_admissions_2019
```

```{r}
hb_admissions <- hospital_admissions %>% 
  group_by(hb) %>% 
  summarise(total_admitted = n()) %>% 
  ggplot() +
  geom_col(aes(x = hb, y = total_admitted), fill = "purple") +
  theme(axis.text.x = element_text(angle = 90))
```

# Joined datasets with location info ####
```{r}
full_admissions <- right_join(locations, hospital_admissions, by = c("hb"))

full_inpatients <- right_join(locations, hospital_inpatients, by = c("hb"))

full_demographics <- right_join(locations, hospital_demographics, by = c("hscp"))

full_specialty <- right_join(locations, hospital_specialty, by = c("hb"))

full_wait_times <- right_join(locations, waiting_times, by = c("location" = "treatment_location")) 
  
  # drop_na(number)
```


```{r}
pre_2020_wait <- full_wait_times %>% 
  select(month, hb, department_type, number_of_attendances_aggregate) %>% 
  filter(month < 202001) %>%
  group_by(hb) %>%
  summarise(total_attendances = sum(number_of_attendances_aggregate)) %>% 
    ggplot() +
    geom_col(aes(x = hb, y = total_attendances)) +
    theme(axis.text.x = element_text(angle = 90))
pre_2020_wait    

post_2020_wait <- full_wait_times %>% 
  select(month, hb, department_type, number_of_attendances_aggregate) %>% 
  filter(month >= 202001) %>%
  group_by(hb) %>%
  summarise(total_attendances = sum(number_of_attendances_aggregate)) %>% 
    ggplot() +
    geom_col(aes(x = hb, y = total_attendances)) +
    theme(axis.text.x = element_text(angle = 90))
post_2020_wait  
```
# Death Data ####
```{r}
deaths_by_age <- read_csv("https://www.opendata.nhs.scot/dataset/5a9ecd07-fcd0-433c-94be-771eb4e0a691/resource/733aad2d-5420-4966-bc34-386a3475623f/download/deaths_hb_agesex_20220302.csv") %>% clean_names()


deaths_by_depriv <- read_csv('https://www.opendata.nhs.scot/dataset/5a9ecd07-fcd0-433c-94be-771eb4e0a691/resource/98648584-4a34-4374-832c-d3f50b6edd80/download/deaths_hb_simd_20220302.csv') %>% clean_names()

deaths_by_hscp <- read_csv("https://www.opendata.nhs.scot/dataset/5a9ecd07-fcd0-433c-94be-771eb4e0a691/resource/3f8e59f9-6133-46db-b8e6-7efed86a8b7c/download/deaths_hscp_agesex_20220302.csv") %>% clean_names()
```

```{r}
death_comp <- deaths_by_age %>% 
  select(hb, deaths, average20152019, sex) %>% 
  group_by(hb) %>% 
  summarise(total_deaths = sum(deaths)) %>% 
  ggplot() +
  geom_col(aes(x = hb, y = total_deaths)) + 
  theme(axis.text.x = element_text(angle = 90))
death_comp

death_comp_2019 <- deaths_by_age %>% 
  select(hb, deaths, average20152019, sex) %>% 
  group_by(hb) %>% 
  summarise(total_deaths = sum(average20152019)) %>% 
  ggplot() +
  geom_col(aes(x = hb, y = total_deaths)) +
  theme(axis.text.x = element_text(angle = 90))
death_comp_2019

death_depriv <- deaths_by_depriv %>% 
  select(simd_quintile, deaths, country) %>% 
  group_by(simd_quintile) %>% 
  summarise(total_deaths = sum(deaths)) %>% 
  ggplot() +
  geom_col(aes(x = simd_quintile, y = total_deaths)) +
  theme(axis.text.x = element_text(angle = 90))
death_depriv

death_trends2 <- deaths_by_age %>% 
  select(hb, deaths, sex, week_ending, average20152019, percent_variation) %>% 
  group_by(week_ending) %>% 
  summarise(total_deaths = sum(deaths)) %>% 
  ggplot() +
  geom_col(aes(x = week_ending, y = total_deaths)) +
  theme(axis.text.x = element_text(angle = 90))
```

```{r}
library(slider)
hospital_trends_full_2020 <- full_demographics %>% 
  #select(number_admissions) %>% 
  mutate(
    admin_moving_avg = slide_dbl(
      .x = number_admissions,
      .f = ~mean(.x),
      before = 100,
      after = 100,
      .complete = TRUE
    )
  ) 
ggplot(hospital_trends_full_2020) +
  geom_col(aes(x = hb, y = admin_moving_avg), colour = "grey") +
  geom_col(aes(x = hb, y = number_admissions), colour = "red") +
  theme(axis.text.x = element_text(angle = 90))
```

```{r}
install.packages("wesanderson")
```

```{r}
library(wesanderson)
install.packages("hrbrthemes")
install.packages("gapminder")
install.packages("ggbump")
library(hrbrthemes) # for plot themes
library(gapminder) # for data
library(ggbump)
```

```{r}
admissions_by_simd <- hospital_admissions %>% 
  select(simd_quintile, admission_type, hb, number_admissions) %>% 
  group_by(simd_quintile) %>% 
  summarise(total_admissions = sum(number_admissions)) %>% 
  ggplot() +
  geom_col(aes(x = simd_quintile, y = total_admissions), colour = "black") +
  theme(axis.text.x = element_text(angle = 90))

admissions_quint_1 <- hospital_admissions %>% 
  select(simd_quintile, admission_type, hb, number_admissions) %>% 
  filter(simd_quintile == 1) %>% 
  group_by(admission_type) %>% 
  summarise(total_admissions = sum(number_admissions)) %>% 
  ggplot() +
  geom_col(aes(x = admission_type, y = total_admissions), colour = "orange") 

admissions_quint_5 <- hospital_admissions %>% 
  select(simd_quintile, admission_type, hb, number_admissions) %>% 
  filter(simd_quintile == 5) %>% 
  group_by(admission_type) %>% 
  summarise(total_admissions = sum(number_admissions)) %>% 
  ggplot() +
  geom_col(aes(x = admission_type, total_admissions), colour = "purple")
  
m_admissions_quint_5 <- hospital_admissions %>% 
  select(simd_quintile, admission_type, hb, number_admissions) %>% 
  filter(simd_quintile == 5) %>% 
  group_by(admission_type) %>% 
  summarise(mean_admissions = mean(number_admissions)) %>% 
  ggplot() +
  geom_col(aes(x = admission_type, mean_admissions)) 
  #scale_fill_manual(values = wes_palette("Darjeeling1", n = 5)) 
  
```

```{r}
admin_specialty_data <- read_csv('../02_cleaned_data/admissions_by_speciality_clean.csv')
```

```{r}
specialty_trends <- admin_specialty_data %>% 
  select(week_ending, specialty, number_admissions) %>% 
  #filter(specialty == "All") %>% 
  group_by(week_ending) %>% 
  summarise(total_admissions = sum(number_admissions)) %>% 
  ggplot() +
  geom_line(aes(x = week_ending, y = total_admissions)) +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Admissions per week")
specialty_trends

specialty_trends_emergency <- admin_specialty_data %>% 
  select(week_ending, specialty, number_admissions) %>% 
  filter(specialty == "Accident & Emergency") %>% 
  group_by(week_ending) %>% 
  summarise(total_admissions = sum(number_admissions)) %>% 
  ggplot() +
  geom_line(aes(x = week_ending, y = total_admissions)) +
  theme(axis.text.x = element_text(angle = 90))

specialty_trends_surgery <- admin_specialty_data %>% 
  select(week_ending, specialty, number_admissions) %>% 
  filter(specialty == "Surgery") %>% 
  group_by(week_ending) %>% 
  summarise(total_admissions = sum(number_admissions)) %>% 
  ggplot() +
  geom_line(aes(x = week_ending, y = total_admissions)) +
  theme(axis.text.x = element_text(angle = 90))

specialty_trends_cardio <-admin_specialty_data %>% 
  select(week_ending, specialty, number_admissions) %>% 
  filter(specialty == "Cardiology") %>% 
  group_by(week_ending) %>% 
  summarise(total_admissions = sum(number_admissions)) %>% 
  ggplot() +
  geom_line(aes(x = week_ending, y = total_admissions)) +
  theme(axis.text.x = element_text(angle = 90))

specialty_trends_cancer <- admin_specialty_data %>% 
  select(week_ending, specialty, number_admissions) %>% 
  filter(specialty == "Cancer") %>% 
  group_by(week_ending) %>% 
  summarise(total_admissions = sum(number_admissions)) %>%  
  ggplot() +
  geom_line(aes(x = week_ending, y = total_admissions)) +
  theme(axis.text.x = element_text(angle = 90))

specialty_trends_community <- admin_specialty_data %>% 
  select(week_ending, specialty, number_admissions) %>% 
  filter(specialty == "Community") %>% 
  group_by(week_ending) %>% 
  summarise(total_admissions = sum(number_admissions)) %>%  
  ggplot() +
  geom_line(aes(x = week_ending, y = total_admissions)) +
  theme(axis.text.x = element_text(angle = 90))

specialty_trends_differ <- admin_specialty_data %>% 
  select(week_ending, specialty, number_admissions, percent_variation) %>% 
  group_by(week_ending) %>% 
  summarise(total_variation = sum(percent_variation)) %>% 
  ggplot() +
  geom_line(aes(x = week_ending, y = total_variation)) +
  theme(axis.text.x = element_text(angle = 90))

specialty_trends_differ2 <- admin_specialty_data %>% 
  select(week_ending, specialty, number_admissions, percent_variation) %>% 
  group_by(week_ending) %>% 
  summarise(mean_variation = mean(percent_variation)) %>% 
  ggplot() +
  geom_line(aes(x = week_ending, y = mean_variation)) +
  theme(axis.text.x = element_text(angle = 90))
  

specialty_trends_differ
specialty_trends_differ2
```
# Updated, cleaned datasets for beds and specialties ####
```{r}
bed_data <- read_csv('../02_cleaned_data/bed_clean.csv')

specialty_data <- read_csv('../02_cleaned_data/specialty_clean.csv')
```

```{r}
bed_trends <- bed_data %>% 
  select(year_quarter, location, shb_name, 
         percentage_occupancy, total_occupied_beddays) %>% 
  group_by(year_quarter) %>% 
  summarise(average_beddays = mean(total_occupied_beddays)) %>% 
  ggplot() +
  geom_line(aes(x = year_quarter, y = average_beddays, group = 1)) +
    theme(axis.text.x = element_text(angle = 90))
  
bed_trends  

bed_trends_occu <- bed_data %>% 
    select(year_quarter, location, shb_name, 
         percentage_occupancy, total_occupied_beddays) %>% 
  group_by(year_quarter) %>% 
  summarise(average_occupancy = mean(percentage_occupancy)) %>%
  drop_na(average_occupancy) %>% 
  ggplot() +
  geom_line(aes(x = year_quarter, y = average_occupancy, group = 1)) +
    theme(axis.text.x = element_text(angle = 90))

bed_trends_occu  
```
# Specialty dataset graphs ####
```{r}
admin_trends <- specialty_data %>% 
  select(year, hb, admission_type, specialty_name, episodes, spells) %>% 
  group_by(year) %>% 
  summarise(total_episodes = sum(episodes)) %>% 
  ggplot() +
  geom_line(aes(x = year, y = total_episodes)) +
  theme(axis.text.x = element_text(angle = 90))
admin_trends

admin_trends_spell <- specialty_data %>% 
  select(year, hb, admission_type, specialty_name, spells) %>% 
  group_by(year) %>% 
  summarise(total_spells = sum(spells)) %>% 
  ggplot() +
  geom_line(aes(x = year, y = total_spells)) 
 # theme(axis.text.x = element_text(angle = 90))
admin_trends_spell

length_per_specialty <- specialty_data %>% 
  select(year, hb, admission_type, average_length_of_episode, spells, specialty_name) %>% 
  group_by(specialty_name) %>% 
  drop_na(average_length_of_episode) %>% 
  ggplot() +
  geom_col(aes(x = specialty_name, y = average_length_of_episode)) +
  theme(axis.text.x = element_text(angle = 90))
length_per_specialty
spells_trend <- specialty_data %>% 
  select(year_quarter, year, location, hb, episodes, length_of_spell, spells) %>% 
  group_by(year_quarter) %>% 
  ggplot() +
  geom_col(aes(x = year_quarter, y = spells)) +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Spells per quarter")
spells_trend
```

```{r}
episodes_per_specialty <- specialty_data %>% 
  select(episodes, specialty_name, hb, length_of_episode) %>% 
  filter(episodes > 1) %>% 
  group_by(specialty_name) %>% 
  summarise(total_episodes = sum(episodes)) %>%
  ggplot() +
  geom_col(aes(x = specialty_name, y = total_episodes)) +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Number of episodes per specialty")
episodes_per_specialty
```

```{r}
variations <- full_demographics %>% 
  select(location_name, percent_variation, admission_type, hb) %>% 
  group_by(hb) %>% 
  ggplot() +
  geom_histogram(aes(x = hb)) +
  theme(axis.text.x = element_text(angle = 90))
variations
```

```{r}
deaths_by_hscp %>% 
  select(age_group, deaths, sex, hscp) %>% 
  group_by(age_group, sex) %>% 
  summarise(total_deaths = sum(deaths)) %>% 
  ggplot() +
  geom_col(aes(x = age_group, y = total_deaths, fill = sex)) +
    theme(axis.text.x = element_text(angle = 90))

```
# Updated datasets with cleaned data ####
```{r}
admission_data <- read_csv('hospital_covid_data/covid_admission_age_sex.csv')

demographic_activity <- read_csv('hospital_covid_data/activity_patient_demographics.csv')

deprivation_activity <- read_csv('hospital_covid_data/activity_deprivation.csv')
```

```{r}
Updated_admission_trends <- admission_data %>% 
  select(year, hb_name, number_admissions, age_group) %>% 
  group_by(year) %>% 
  summarise(total_admissions = sum(number_admissions)) %>% 
  ggplot() +
  geom_col(aes(x = year, y = total_admissions))
Updated_admission_trends

Updated_admission_trends_2020 <- admission_data %>% 
  select(year, hb_name, number_admissions, age_group, month) %>% 
  filter(year == 2020) %>% 
  group_by(month) %>% 
  summarise(avg_admissions = sum(number_admissions)) %>% 
  ggplot() +
  geom_line(aes(x = month, y = avg_admissions))
Updated_admission_trends_2020

Updated_admission_trends_2021 <- admission_data %>% 
  select(year, hb_name, number_admissions, age_group, month) %>% 
  filter(year == 2021) %>% 
  group_by(month) %>% 
  summarise(sum_admissions = sum(number_admissions)) %>% 
  ggplot() +
  geom_line(aes(x = month, y = sum_admissions))
Updated_admission_trends_2021

Updated_admission_trends_2022 <- admission_data %>% 
  select(year, hb_name, number_admissions, age_group, month) %>% 
  filter(year == 2022) %>% 
  group_by(month) %>% 
  summarise(sum_admissions = sum(number_admissions)) %>% 
  ggplot() +
  geom_line(aes(x = month, y = sum_admissions))
Updated_admission_trends_2022
library(lubridate)

admission_data2 <- admission_data %>% 
  mutate(month_name = month(month, label = TRUE, abbr = FALSE))

admission_data

# admission_data2 <- admission_data %>% 
#   mutate(month_name = recode(month,
#                              1 = "January",
#                              2 = "February",
#                              3 = "March", 
#                              4 = "April",
#                              5 = "May", 
#                              6 = "June",
#                              7 = "July",
#                              8 = "August", 
#                              9 = "September",
#                              10 = "October",
#                              11 = "November",
#                              12 = "December"))

Updated_admission_trends_winter <- admission_data2 %>% 
  select(year, hb_name, number_admissions, age_group, month_name, day) %>% 
  filter(month_name %in% c("January", "February", "December"))%>% 
  group_by(month_name) %>% 
  summarise(total_admissions = sum(number_admissions)) %>% 
  ggplot() +
  geom_col(aes(x = month_name, y = total_admissions), fill = "#56B4E9")
Updated_admission_trends_winter  
```

```{r}
death_trends <- deaths_by_age %>% 
  mutate(week_ending = ymd(week_ending)) %>%
  filter(age_group == "All ages", 
         sex == "All",
         hb == "S92000003") %>% 
  #select(week_ending, age_group, deaths, sex, hb) %>% 
  #group_by(week_ending, hb) %>% 
  #mutate(avg_deaths = mean(deaths)) %>% 
  ggplot() +
  geom_line(aes(x = week_ending, y = deaths)) +
  #scale_x_continuous(breaks = c("20200105")) +
  #theme(axis.text.x = element_text(angle = 90))
death_trends
```

```{r}
depriv_trends <- deprivation_activity %>% 
  select(year, location, stays, admission_type, simd) %>% 
  group_by(year, simd) %>% 
  drop_na(simd) %>% 
  summarise(total_stays = sum(stays)) %>% 
  ggplot() +
  geom_col(aes(x = year, y = total_stays, fill = simd))
depriv_trends
```

```{r}
stays_per_admissiontype <- demographic_activity %>% 
  select(sex, episodes, age, year, admission_type, location, length_of_stay) %>% 
  group_by(admission_type, age) %>% 
  summarise(total_staylength = sum(length_of_stay)) %>% 
  ggplot() +
  geom_col(aes(x = admission_type, y = total_staylength, fill = age)) + 
  theme(axis.text.x = element_text(angle = 90))
stays_per_admissiontype  
```

```{r}
stays_per_location <- demographic_activity %>% 
  select(location, stays, admission_type, sex, year, location_name) %>% 
  group_by(location_name, year) %>% 
  summarise(total_stays = sum(stays)) %>% 
  ggplot() +
  geom_col(aes(x = location_name, y = total_stays, fill = year)) +
  theme(axis.text.x = element_text(angle = 90))
```

```{r}
demographic_trends <- demographic_activity %>% 
  select(admission_type, year, location, age, stays, location_name) %>% 
  group_by(year) %>% 
  summarise(avg_stays = mean(stays)) %>% 
  ggplot() +
  geom_line(aes(x = year, y = avg_stays)) 
  
```

```{r}
# admission_data2 %>% 
#   distinct(admission_type)

Hospitalisation_trends <- admission_data2 %>% 
  select(month_name, hb_name, year, admission_type, month_name, number_admissions) %>% 
  #filter(admission_type == "Emergency") %>% 
  group_by(month_name) %>% 
  summarise(total_admin = sum(number_admissions)) %>% 
  ggplot() +
  geom_line(aes(x = month_name, y = total_admin, group = 1)) +
  ggtitle("Trend of Admissions over the year")
Hospitalisation_trends

Hospitalisation_differ <- admission_data2 %>% 
  select(month_name, hb_name, year, admission_type, percent_variation) %>% 
  #filter(admission_type == "Emergency") %>% 
  group_by(month_name) %>% 
  summarise(total_diff = sum(percent_variation)) %>% 
  ggplot() +
  geom_line(aes(x = month_name, y = total_diff, group = 1)) +
  ggtitle("Trend of total variation from norm")
Hospitalisation_differ

Hospitalisation_differ2 <- admission_data2 %>% 
  select(month_name, hb_name, year, admission_type, percent_variation) %>% 
  #filter(admission_type == "Emergency") %>% 
  group_by(month_name) %>% 
  summarise(mean_diff = mean(percent_variation)) %>% 
  ggplot() +
  geom_line(aes(x = month_name, y = mean_diff, group = 1)) +
  ggtitle("Trend of average variation from norm")
Hospitalisation_differ2
```
# Lubridated death datasets ####
```{r}
library(lubridate)
deaths_by_depriv2 <- deaths_by_depriv %>%
  mutate(week_ending = ymd(week_ending))
```

```{r}
deaths_by_depriv
deaths_by_age
deaths_by_hscp
```

```{r}
deaths_by_age2 <- deaths_by_age %>% 
  mutate(week_ending = ymd(week_ending)) %>% 
  mutate(year = year(week_ending),
         month = month(week_ending),
         day = day(week_ending)) %>% 
  mutate(month_name = month(month, label = TRUE, abbr = FALSE))
```

```{r}
Final_death_graph1 <- deaths_by_depriv2 %>% 
  select(week_ending, simd_quintile, deaths, average20152019) %>% 
  filter(simd_quintile == 1) %>% 
  group_by(week_ending) %>% 
  ggplot() +
  geom_line(aes(x = week_ending, y = deaths), colour = "red") +
  geom_line(aes(x = week_ending, y = average20152019), colour = "blue") +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Trend of deaths for SIMD 1")
Final_death_graph1 

Final_death_graph2 <- deaths_by_depriv2 %>% 
  select(week_ending, simd_quintile, deaths, average20152019) %>% 
  filter(simd_quintile == 2) %>% 
  group_by(week_ending) %>% 
  ggplot() +
  geom_line(aes(x = week_ending, y = deaths), colour = "red") +
  geom_line(aes(x = week_ending, y = average20152019), colour = "blue") +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Trend of deaths for SIMD 2") +
  labs()
Final_death_graph2

Final_death_graph3 <- deaths_by_depriv2 %>% 
  select(week_ending, simd_quintile, deaths, average20152019) %>% 
  #filter(simd_quintile == 1) %>% 
  group_by(week_ending) %>% 
  ggplot() +
  geom_line(aes(x = week_ending, y = deaths), colour = "red") +
  geom_line(aes(x = week_ending, y = average20152019), colour = "blue") +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Trend of deaths for SIMDs")+
  xlab("Trend per month") 
  #scale_x_continuous(labels = month(week_ending, labels = TRUE))
Final_death_graph3

Final_death_graph4 <- deaths_by_depriv2 %>% 
  select(week_ending, simd_quintile, deaths, average20152019) %>% 
  filter(simd_quintile == 3) %>% 
  group_by(week_ending) %>% 
  ggplot() +
  geom_line(aes(x = week_ending, y = deaths), colour = "red") +
  geom_line(aes(x = week_ending, y = average20152019), colour = "blue") +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Trend of deaths for SIMD 3")
Final_death_graph4

Final_death_graph5 <- deaths_by_depriv2 %>% 
  select(week_ending, simd_quintile, deaths, average20152019) %>% 
  filter(simd_quintile == 4) %>% 
  group_by(week_ending) %>% 
  ggplot() +
  geom_line(aes(x = week_ending, y = deaths), colour = "red") +
  geom_line(aes(x = week_ending, y = average20152019), colour = "blue") +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Trend of deaths for SIMD 4")
Final_death_graph5

Final_death_graph6 <- deaths_by_depriv2 %>% 
  select(week_ending, simd_quintile, deaths, average20152019) %>% 
  filter(simd_quintile == 5) %>% 
  group_by(week_ending) %>% 
  ggplot() +
  geom_line(aes(x = week_ending, y = deaths), colour = "red") +
  geom_line(aes(x = week_ending, y = average20152019), colour = "blue") +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Trend of deaths for SIMD 5")
Final_death_graph6
```

```{r}
Death_trends_age_2020 <- deaths_by_age2 %>% 
  select(year, month_name, deaths, average20152019, age_group) %>% 
  group_by(month_name, average20152019) %>% 
  filter(year == 2020) %>% 
  summarise(avg_deaths = mean(deaths)) %>% 
  ggplot() +
  geom_line(aes(x = month_name, y = avg_deaths), colour = "red") +
  geom_line(aes(x = month_name, y = average20152019), colour = "blue") +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Trend of deaths by month")
Death_trends_age_2020

Death_trends_age_2021 <- deaths_by_age2 %>% 
  select(year, month_name, deaths, average20152019, age_group, week_ending) %>% 
  group_by(week_ending, average20152019) %>% 
  filter(year == 2021) %>% 
  summarise(avg_deaths = mean(deaths)) %>% 
  ggplot() +
  geom_line(aes(x = week_ending, y = avg_deaths), colour = "red") +
  geom_line(aes(x = week_ending, y = average20152019), colour = "blue") +
  ggtitle("Trend of deaths by week 2021")
Death_trends_age_2021

Death_trends_age_2022 <- deaths_by_age2 %>% 
  select(year, month_name, deaths, average20152019, age_group, week_ending, day) %>% 
  group_by(month_name, average20152019) %>% 
  filter(year == 2022) %>% 
  summarise(avg_deaths = mean(deaths)) %>% 
  ggplot() +
  geom_col(aes(x = month_name, y = average20152019), fill = "blue") +
  geom_col(aes(x = month_name, y = avg_deaths), fill = "red") +
  
  ggtitle("Trend of deaths by month 2022")
Death_trends_age_2022

Death_trends_per_age <- deaths_by_age2 %>% 
  select(year, month_name, deaths, average20152019, age_group, day) %>% 
  group_by(age_group, average20152019) %>% 
  summarise(total_deaths = sum(deaths)) %>% 
  ggplot() +
  geom_col(aes(x = age_group, y = total_deaths), fill = "red") +
  geom_col(aes(x = age_group, y = average20152019), fill = "blue") +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Trend of deaths per age group")
```

```{r}
deaths_by_hscp2 <- deaths_by_hscp %>% 
  mutate(week_ending = ymd(week_ending)) %>% 
  mutate(year = year(week_ending),
         month = month(week_ending),
         day = day(week_ending)) %>% 
  mutate(month_name = month(month, label = TRUE, abbr = FALSE))

hscp_trends_2020 <- deaths_by_hscp2 %>% 
  select(week_ending, year, month_name, age_group, deaths, average20152019) %>% 
  filter(year == 2020) %>% 
  group_by(month_name, average20152019) %>% 
  ggplot() +
  geom_col(aes(x = month_name, y = deaths), fill = "red") + 
  geom_col(aes(x = month_name, y = average20152019), fill = "blue") +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Trend of HSCP deaths by month 2020")
hscp_trends_2020

hscp_trends_2021 <- deaths_by_hscp2 %>% 
  select(week_ending, year, month_name, age_group, deaths, average20152019) %>% 
  filter(year == 2021) %>% 
  group_by(month_name, average20152019) %>% 
  ggplot() +
  geom_col(aes(x = month_name, y = deaths), fill = "red") +
  geom_col(aes(x = month_name, y = average20152019), fill = "blue") +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Trend of HSCP deaths by month 2021")
hscp_trends_2021
```

```{r}
deaths_by_hscp2 %>% 
  select(week_ending, year, month_name, age_group, deaths, hscp, average20152019) %>% 
  group_by(month_name, hscp, average20152019) %>% 
  ggplot() +
  geom_col(aes(x = hscp, y = deaths), fill = "red") +
  geom_col(aes(x = hscp, y = average20152019), fill = "blue") +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Trend of deaths per hscp")
```

```{r}
deaths_by_age2 %>% 
  select(age_group, deaths, average20152019, hb, year, month_name) %>% 
  group_by(age_group, hb, average20152019) %>% 
  summarise(total_deaths = sum(deaths)) %>% 
  ggplot() +
  geom_col(aes(x = hb, y = total_deaths), fill = "red") +
  geom_col(aes(x = hb, y = average20152019), fill = "blue") +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Trend of deaths per HB")
```

```{r}
deaths_by_age2 %>% 
  select(percent_variation, year, month_name, age_group, hb, sex) %>% 
  group_by(month_name, percent_variation, sex) %>% 
  ggplot() +
  geom_col(aes(x = month_name, y = percent_variation, fill = sex)) +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Trend of death variation")
```

```{r}
deaths_by_hscp2 %>% 
  select(hscp, sex, deaths, average20152019, age_group, year, month_name) %>% 
  group_by(month_name, sex, hscp) %>% 
  summarise(mean_deaths = mean(deaths)) %>% 
  ggplot() +
  geom_col(aes(x = month_name, y = mean_deaths, fill = sex)) +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Mean deaths by month")
```
# HSCP death graphs ####
```{r}
deaths_by_hscp2 %>% 
  select(hscp, sex, deaths, average20152019, age_group, year, month_name) %>% 
  group_by(month_name, sex, hscp) %>% 
  filter(sex == "Female") %>% 
  summarise(mean_deaths = mean(deaths)) %>% 
  ggplot() +
  geom_col(aes(x = month_name, y = mean_deaths, fill = sex)) +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Mean deaths by month - Female")
```

```{r}
deaths_by_hscp2 %>% 
  select(hscp, sex, deaths, average20152019, age_group, year, month_name) %>% 
  group_by(month_name, sex, hscp) %>% 
  filter(sex == "Male") %>% 
  summarise(mean_deaths = mean(deaths)) %>% 
  ggplot() +
  geom_col(aes(x = month_name, y = mean_deaths, fill = sex)) +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Mean deaths by month - Male")
```

```{r}
deaths_by_depriv3 <- deaths_by_depriv2 %>% 
  mutate(week_ending = ymd(week_ending)) %>% 
  mutate(year = year(week_ending),
         month = month(week_ending),
         day = day(week_ending)) %>% 
  mutate(month_name = month(month, label = TRUE, abbr = FALSE))
deaths_by_depriv3

deaths_by_depriv3 %>% 
  select(year, average20152019, deaths, month_name, simd_quintile) %>% 
  group_by(month_name, simd_quintile, deaths) %>% 
  summarise(mean_deaths = mean(deaths)) %>% 
  ggplot() +
  geom_col(aes(x = month_name, y = mean_deaths, fill = simd_quintile)) +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Quintile deaths per month")
```

```{r}
rolling_deaths <- deaths_by_age2 %>% 
  mutate(
    moving_avg_death = slide_dbl(
      .x = deaths,
      .f = ~mean(.x),
      before = 1000, 
      after = 1000
    )
  )
ggplot(rolling_deaths) + 
  geom_line(aes(x = week_ending, y = moving_avg_death), colour = "grey") + 
  geom_line(aes(x = week_ending, y = deaths), colour = "red") 
 
```

